### ISSUE TITLE
oak saplings in the reactor access port can be picked and taken out

### ISSUE THREAD

**Issue by Ritwik-main** [PranavVerma-droid/AdvancedTech#10]
### Checklist

- [X] You are using official & LATEST version downloaded from Builds (https://github.com/PranavVerma-droid/AdvancedTech/releases)
- [X] You did not modify the jar file
- [X] You searched existing issues, and could not find any existing bug report on this

### Description

the oak saplings named start and stop can be dragged into your inventory and used for other purposes like planting

### Reproduction Steps

pull the saplings out

### Expected Behavior

the saplings should be virtual and non useable

### Server Software

Paper

### Minecraft Version

1.20.x

### Slimefun version

rc-35

### Plugin version

Dev version 1.0.0.0

**Comment by PranavVerma-droid** [comment]
I have Fixed the Issue, Please Check the Latest Dev Build:
https://thebusybiscuit.github.io/builds/PranavVerma-droid/AdvancedTech/dev/
