### ISSUE TITLE
Enhanced Crafting Table Slot Issue

### ISSUE THREAD

**Issue by Shrivanth-2A7** [PranavVerma-droid/AdvancedTech#20]
There is a bug in crafting some items in the enhanced crafting table. When i place an item in the first slot, every item in the dispenser gets freezed and fixed. Couldnt get the items by clicking but got the items back by breaking the dispenser. So yeah this is the issue.

**Comment by PranavVerma-droid** [comment]
Confirmed As a Issue, Working on Fixing this.

**Comment by PranavVerma-droid** [comment]
Fixed. #23
