### ISSUE TITLE
Could not pass event InventoryClickEvent to AdvancedTech vDEV - 18 (git 42340de6)

### ISSUE THREAD

**Issue by lonng12** [PranavVerma-droid/AdvancedTech#22]
![image](https://github.com/PranavVerma-droid/AdvancedTech/assets/74055318/2a139e8c-9c9e-47a6-b9f1-dd16545a071b)
![image](https://github.com/PranavVerma-droid/AdvancedTech/assets/74055318/68dc3a68-4640-4918-921c-bb907cb30584)

**Comment by PranavVerma-droid** [comment]
Confirmed Issue, Working to Fix it.

**Comment by PranavVerma-droid** [comment]
Fixed. #23
