### ISSUE TITLE
Carbando V2 Recipe problem

### ISSUE THREAD

**Issue by Leopord2** [PranavVerma-droid/AdvancedTech#4]
### Checklist

- [X] You are using official & LATEST version downloaded from Builds (https://github.com/PranavVerma-droid/AdvancedTech/releases)
- [X] You did not modify the jar file
- [X] You searched existing issues, and could not find any existing bug report on this

### Description

The Boosted Carbanado which is to be crafted in pressure chamber.... So slimefun book says it needs 4 carbanado for 1 boosted carbanado. But when im crafting... its like... 1 carbanado = 1 boosted carbanado. So 4 carbanado arent getting used up to get 1 boosted one. It only takes in 1 and gives the boosted carbanado.

### Reproduction Steps

put 1 carbanado inside the pressure chamber. You will get boosted carbanado instantly after using it.

### Expected Behavior

4 carbanados should be used for making 1 boosted carbanado.

### Server Software

Paper

### Minecraft Version

1.20.x

### Slimefun version

Your server.....

### Plugin version

DEV - 1081 (git aebab92e)

**Comment by PranavVerma-droid** [comment]
Yep, Verified as a Issue.
![image](https://github.com/PranavVerma-droid/AdvancedTech/assets/73458565/25a25257-4187-4a91-bfcc-c9269210ddf0)

**Comment by PranavVerma-droid** [comment]
Updating to [AdvancedTech V1.0.0](https://github.com/PranavVerma-droid/AdvancedTech/releases).
